AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'Pokemon DynamoDB REST API using Lambda and API Gateway'

Parameters:
  TableName:
    Type: String
    Default: pokemon23
    Description: DynamoDB table name

  AwsRegion:
    Type: String
    Default: eu-west-1
    Description: AWS region

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: python3.9
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        TABLENAME: !Ref TableName
  Api:
    TracingEnabled: true

Conditions:
  IsProduction: !Equals [!Ref "AWS::StackName", "api-pokemon-prod"]

Resources:
  PokemonApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      #FunctionName: pokemon-api
      CodeUri: pokemon/
      Handler: app.lambda_handler
      Description: Pokemon DynamoDB REST API
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLENAME: !Ref TableName
          AWSREGION: !Ref AwsRegion

      AutoPublishAlias: live
      DeploymentPreference:
        Type: !If [IsProduction, "Canary10Percent5Minutes", "AllAtOnce"] # only do canary deployment in prod
        Alarms: !If [IsProduction, [!Ref CanaryErrorsAlarm], []]

      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: GET

        GetAllPokemon:
          Type: Api
          Properties:
            Path: /pokemon
            Method: GET

        GetPokemonById:
          Type: Api
          Properties:
            Path: /pokemon/{id}
            Method: GET

        GetPokemonByName:
          Type: Api
          Properties:
            Path: /pokemon/name/{name}
            Method: GET

        GetPokemonByType:
          Type: Api
          Properties:
            Path: /pokemon/type/{type}
            Method: GET

        SearchPokemon:
          Type: Api
          Properties:
            Path: /search
            Method: GET

        ApiDocs:
          Type: Api
          Properties:
            Path: /docs
            Method: GET

      Tags:
        Project: Pokemon

  CanaryErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda function canary errors
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      Dimensions:
        - Name: Resource
          Value: !Sub "${PokemonApiFunction}:live"
        - Name: FunctionName
          Value: !Ref PokemonApiFunction
        - Name: ExecutedVersion
          Value: !GetAtt PokemonApiFunction.Version.Version


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-Pokemon-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  PokemonApiEndpoint:
    Description: Pokemon API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/pokemon/'
  PokemonApiFunctionIamRole:
    Description: Implicit IAM Role created for Pokemon function
    Value: !GetAtt PokemonApiFunctionRole.Arn
